const PERSONALITY_TRAITS = [
   { id: 't1', traitHeading: 'T1 — Structure & Flexibility', name: 'Structure & Flexibility', leftLabel: 'Order & Planning', rightLabel: 'Spontaneity & Adaptability' },
   { id: 't2', traitHeading: 'T2 — Social Energy', name: 'Social Energy', leftLabel: 'Solitude Recharge', rightLabel: 'People Recharge' },
   { id: 't3', traitHeading: 'T3 — Self-Expression Style', name: 'Self-Expression Style', leftLabel: 'Reserved Processing', rightLabel: 'Open Expression' },
   { id: 't4', traitHeading: 'T4 — Risk Tolerance', name: 'Risk Tolerance', leftLabel: 'Security-Oriented', rightLabel: 'Opportunity-Oriented' },
   { id: 't5', traitHeading: 'T5 — Pace of Life', name: 'Pace of Life', leftLabel: 'Measured Rhythm', rightLabel: 'Fast Action' },
   { id: 't6', traitHeading: 'T6 — Thought Tempo', name: 'Thought Tempo', leftLabel: 'Deliberate Processing', rightLabel: 'Rapid Thinking' },
   { id: 't7', traitHeading: 'T7 — Decision Style', name: 'Decision Style', leftLabel: 'Logic-Led', rightLabel: 'Intuition-Led' },
   { id: 't8', traitHeading: 'T8 — Social Preference', name: 'Social Preference', leftLabel: '1:1 Depth', rightLabel: 'Group Orientation' },
   { id: 't9', traitHeading: 'T9 — Emotional Regulation', name: 'Emotional Regulation', leftLabel: 'Reactive', rightLabel: 'Stable & Recovering' },
   { id: 't10', traitHeading: 'T10 — Conscientiousness (Execution Reliability)', name: 'Conscientiousness (Execution Reliability)', leftLabel: 'Flexible Execution', rightLabel: 'Consistent Execution' },
   { id: 't11', traitHeading: 'T11 — Autonomy Preference', name: 'Autonomy Preference', leftLabel: 'Guidance & Structure', rightLabel: 'Independence & Ownership' },
];

// 44 deterministic items (11 traits × 4). Each item uses the same 1..7 scale.
const PERSONALITY_QUESTIONS = [
   { id: 't1_q1', traitId: 't1', domain: 'general', prompt: 'Over a typical week, your approach is…', leftAnchor: 'Plan everything ahead and follow a clear routine', rightAnchor: 'Keep everything open, decide in the moment', options: ['Plan everything ahead and follow a clear routine', 'Plan most things and keep small flexibility', 'Plan key parts, adjust smaller details', 'Balance planning and flexibility equally', 'Keep a loose plan, adapt often', 'Decide as things unfold, minimal planning', 'Keep everything open, decide in the moment'] },
   { id: 't1_q2', traitId: 't1', domain: 'general', prompt: 'When plans change unexpectedly, you…', leftAnchor: 'Re-plan quickly to restore structure', rightAnchor: 'Enjoy change and feel energized by it', options: ['Re-plan quickly to restore structure', 'Try to return to original plan', 'Adjust, but prefer stability', 'Adjust based on situation and importance', 'Adapt without much stress', 'Shift quickly and stay comfortable', 'Enjoy change and feel energized by it'] },
   { id: 't1_q3', traitId: 't1', domain: 'general', prompt: 'In daily life, you function best with…', leftAnchor: 'Clear systems, routines, and defined structure', rightAnchor: 'No fixed systems, complete freedom', options: ['Clear systems, routines, and defined structure', 'Mostly structured with limited flexibility', 'Structured core with some flexibility', 'Equal mix of structure and freedom', 'Flexible system with light structure', 'Minimal systems, mostly adaptive', 'No fixed systems, complete freedom'] },
   { id: 't1_q4', traitId: 't1', domain: 'general', prompt: 'Your natural planning horizon is…', leftAnchor: 'Plan far ahead with clear timelines', rightAnchor: 'Focus on the present, decide as needed', options: ['Plan far ahead with clear timelines', 'Prefer long-term direction and clarity', 'Think ahead while staying flexible', 'Balance short-term and long-term focus', 'Focus mostly on near-term adjustments', 'Rarely plan far ahead', 'Focus on the present, decide as needed'] },

   { id: 't2_q1', traitId: 't2', domain: 'general', prompt: 'After a demanding day, you recharge best by…', leftAnchor: 'Spending quiet time alone', rightAnchor: 'Being around people and interaction', options: ['Spending quiet time alone', 'Being alone with minimal interaction', 'Having some space before reconnecting', 'Mixing alone time and social time equally', 'Being around a few people', 'Spending time in active social settings', 'Being around people and interaction'] },
   { id: 't2_q2', traitId: 't2', domain: 'general', prompt: 'In extended social situations, your energy…', leftAnchor: 'Drops quickly; I need to step away', rightAnchor: 'Increases the longer it continues', options: ['Drops quickly; I need to step away', 'Gradually drains over time', 'Slightly decreases but manageable', 'Depends on people and environment', 'Slightly increases over time', 'Builds as interaction continues', 'Increases the longer it continues'] },
   { id: 't2_q3', traitId: 't2', domain: 'general', prompt: 'When something exciting happens, you…', leftAnchor: 'Process it privately before sharing', rightAnchor: 'Immediately share and involve others', options: ['Process it privately before sharing', 'Share with one trusted person', 'Reflect briefly, then share selectively', 'Share depending on situation', 'Share fairly soon with others', 'Naturally tell multiple people', 'Immediately share and involve others'] },
   { id: 't2_q4', traitId: 't2', domain: 'general', prompt: 'Too much time alone makes you feel…', leftAnchor: 'Fully comfortable and restored', rightAnchor: 'Disconnected without people', options: ['Fully comfortable and restored', 'Mostly calm and content', 'Slightly comfortable', 'Neutral—can go either way', 'Slightly restless', 'Restless and seeking interaction', 'Disconnected without people'] },

   { id: 't3_q1', traitId: 't3', domain: 'general', prompt: 'When something is on your mind, you…', leftAnchor: 'Process internally before speaking', rightAnchor: 'Speak immediately to process thoughts', options: ['Process internally before speaking', 'Think privately, then share selectively', 'Reflect first, then express', 'Sometimes process internally, sometimes externally', 'Start sharing while still processing', 'Express openly as thoughts form', 'Speak immediately to process thoughts'] },
   { id: 't3_q2', traitId: 't3', domain: 'general', prompt: 'In conversations, you tend to…', leftAnchor: 'Listen first, speak after forming thoughts', rightAnchor: 'Speak quickly as thoughts arrive', options: ['Listen first, speak after forming thoughts', 'Speak selectively after understanding', 'Pause briefly before responding', 'Adjust based on topic and comfort', 'Speak fairly often while thinking', 'Express while forming ideas', 'Speak quickly as thoughts arrive'] },
   { id: 't3_q3', traitId: 't3', domain: 'general', prompt: 'When emotionally affected, you usually…', leftAnchor: 'Go quiet and process internally', rightAnchor: 'Express immediately without holding back', options: ['Go quiet and process internally', 'Take space, then share later', 'Need time, then express partially', 'Adjust based on safety and situation', 'Express fairly soon with some pauses', 'Share quickly and openly', 'Express immediately without holding back'] },
   { id: 't3_q4', traitId: 't3', domain: 'general', prompt: 'When explaining something, your style is…', leftAnchor: 'Concise and to the point', rightAnchor: 'Highly expressive with rich detail', options: ['Concise and to the point', 'Brief with minimal detail', 'Mostly concise with some detail', 'Adjust based on audience', 'Fairly detailed but structured', 'Expressive with context and detail', 'Highly expressive with rich detail'] },

   { id: 't4_q1', traitId: 't4', domain: 'general', prompt: 'When facing uncertain opportunities, you…', leftAnchor: 'Wait for clarity before taking action', rightAnchor: 'Move quickly and learn through action', options: ['Wait for clarity before taking action', 'Prefer safety and predictable outcomes', 'Take small, cautious steps forward', 'Weigh risk and reward before acting', 'Move forward if upside feels meaningful', 'Act despite uncertainty and adjust later', 'Move quickly and learn through action'] },
   { id: 't4_q2', traitId: 't4', domain: 'general', prompt: 'You feel most engaged when…', leftAnchor: 'Everything is stable and predictable', rightAnchor: 'In high-uncertainty, high-growth environments', options: ['Everything is stable and predictable', 'Mostly secure with limited uncertainty', 'Slightly challenged but stable', 'Balanced between stability and challenge', 'Facing some uncertainty and growth', 'Exploring new and uncertain situations', 'In high-uncertainty, high-growth environments'] },
   { id: 't4_q3', traitId: 't4', domain: 'general', prompt: 'In major decisions, you tend to…', leftAnchor: 'Protect what is already secure', rightAnchor: 'Act quickly when upside is strong', options: ['Protect what is already secure', 'Prioritize stability over change', 'Take cautious, low-risk steps', 'Balance safety and opportunity', 'Take calculated risks for growth', 'Lean toward bold opportunities', 'Act quickly when upside is strong'] },
   { id: 't4_q4', traitId: 't4', domain: 'general', prompt: 'When failure is possible, you usually…', leftAnchor: 'Avoid risk unless absolutely necessary', rightAnchor: 'Embrace risk as part of progress', options: ['Avoid risk unless absolutely necessary', 'Choose safer options to reduce loss', 'Take limited risk with safeguards', 'Balance potential loss and gain', 'Accept some risk for meaningful upside', 'Take risks to pursue strong outcomes', 'Embrace risk as part of progress'] },

   { id: 't5_q1', traitId: 't5', domain: 'general', prompt: 'Your natural pace in most weeks is…', leftAnchor: 'Slow, steady, and unhurried', rightAnchor: 'Very fast, high-energy, constantly moving', options: ['Slow, steady, and unhurried', 'Mostly calm with low urgency', 'Steady with occasional bursts of speed', 'Balanced between calm and fast', 'Generally fast with some slow periods', 'Fast-paced and active most of the time', 'Very fast, high-energy, constantly moving'] },
   { id: 't5_q2', traitId: 't5', domain: 'general', prompt: 'When tasks pile up, you tend to…', leftAnchor: 'Work through them calmly over time', rightAnchor: 'Speed up sharply and clear everything fast', options: ['Work through them calmly over time', 'Stay steady and avoid rushing', 'Increase pace slightly', 'Adjust speed based on priority', 'Move faster while staying controlled', 'Work quickly to clear tasks', 'Speed up sharply and clear everything fast'] },
   { id: 't5_q3', traitId: 't5', domain: 'general', prompt: 'In daily life, you prefer a rhythm that feels…', leftAnchor: 'Calm, spacious, and unhurried', rightAnchor: 'Constantly moving with high momentum', options: ['Calm, spacious, and unhurried', 'Mostly relaxed with low pressure', 'Calm with occasional activity', 'Balanced between calm and active', 'Active with some recovery time', 'Highly active and dynamic', 'Constantly moving with high momentum'] },
   { id: 't5_q4', traitId: 't5', domain: 'general', prompt: 'When you have free time, you usually…', leftAnchor: 'Slow down and fully recharge', rightAnchor: 'Avoid idleness and stay constantly engaged', options: ['Slow down and fully recharge', 'Rest intentionally and recover', 'Mostly relax with some activity', 'Choose rest or activity based on mood', 'Stay active but include recovery', 'Fill time with activity or projects', 'Avoid idleness and stay constantly engaged'] },

   { id: 't6_q1', traitId: 't6', domain: 'general', prompt: 'Your mind during a typical day feels…', leftAnchor: 'Quiet, focused on one thing at a time', rightAnchor: 'Fast and constantly moving between ideas', options: ['Quiet, focused on one thing at a time', 'Mostly calm with steady focus', 'Calm with occasional thought bursts', 'Balanced between calm and active', 'Active with frequent idea shifts', 'Busy with many thoughts at once', 'Fast and constantly moving between ideas'] },
   { id: 't6_q2', traitId: 't6', domain: 'general', prompt: 'When processing new information, you…', leftAnchor: 'Take time to analyze step by step', rightAnchor: 'Understand instantly and move on', options: ['Take time to analyze step by step', 'Prefer steady and thoughtful processing', 'Process carefully but not slowly', 'Adjust speed based on complexity', 'Process fairly quickly', 'Interpret quickly and respond fast', 'Understand instantly and move on'] },
   { id: 't6_q3', traitId: 't6', domain: 'general', prompt: 'In conversations, you tend to…', leftAnchor: 'Pause and think before responding', rightAnchor: 'Speak as thoughts arrive instantly', options: ['Pause and think before responding', 'Take a moment, then reply carefully', 'Respond after brief reflection', 'Adjust speed based on topic', 'Respond quickly', 'Think while speaking', 'Speak as thoughts arrive instantly'] },
   { id: 't6_q4', traitId: 't6', domain: 'general', prompt: 'Under pressure, your thinking becomes…', leftAnchor: 'Narrow and highly focused', rightAnchor: 'Rapid and constantly shifting', options: ['Narrow and highly focused', 'More controlled and steady', 'Slightly more focused', 'Changes depending on situation', 'More active with extra thoughts', 'Fast and mentally busy', 'Rapid and constantly shifting'] },

   { id: 't7_q1', traitId: 't7', domain: 'general', prompt: 'When making decisions, you rely more on…', leftAnchor: 'Logic, data, and structured analysis', rightAnchor: 'Strong gut feeling without needing logic', options: ['Logic, data, and structured analysis', 'Reasoning and objective thinking', 'Mostly logic with some intuition', 'Equal mix of logic and intuition', 'Intuition with some reasoning', 'Inner instinct over detailed analysis', 'Strong gut feeling without needing logic'] },
   { id: 't7_q2', traitId: 't7', domain: 'general', prompt: 'When choices are unclear, you…', leftAnchor: 'Gather more data before deciding', rightAnchor: 'Act on intuition immediately', options: ['Gather more data before deciding', 'Seek clarity through analysis', 'Use logic, then decide', 'Balance analysis and instinct', 'Decide, then validate with reasoning', 'Trust instinct and adjust later', 'Act on intuition immediately'] },
   { id: 't7_q3', traitId: 't7', domain: 'general', prompt: 'When something feels right but lacks logic, you…', leftAnchor: 'Reject it and rely on facts', rightAnchor: 'Act on it without justification', options: ['Reject it and rely on facts', 'Strongly question it', 'Remain cautious about it', 'Weigh both feeling and logic', 'Consider it seriously', 'Trust it often', 'Act on it without justification'] },
   { id: 't7_q4', traitId: 't7', domain: 'general', prompt: 'When choosing between options, you prefer what…', leftAnchor: 'Is rational and clearly justified', rightAnchor: 'Feels right regardless of logic', options: ['Is rational and clearly justified', 'Makes logical sense', 'Is practical and reasoned', 'Balances logic and meaning', 'Feels aligned and meaningful', 'Resonates internally', 'Feels right regardless of logic'] },

   { id: 't8_q1', traitId: 't8', domain: 'general', prompt: 'Socially, you feel most like yourself in…', leftAnchor: 'Deep one-on-one conversations', rightAnchor: 'Large, energetic social environments', options: ['Deep one-on-one conversations', 'Small, meaningful interactions', 'Small groups with some depth', 'Comfortable in both small and group settings', 'Group interactions with some depth', 'Larger, active social groups', 'Large, energetic social environments'] },
   { id: 't8_q2', traitId: 't8', domain: 'general', prompt: 'At social gatherings, you usually…', leftAnchor: 'Stay in one meaningful conversation', rightAnchor: 'Thrive in high-energy group settings', options: ['Stay in one meaningful conversation', 'Stick with a small circle', 'Move slowly between a few people', 'Balance depth and group interaction', 'Engage with multiple people', 'Move easily within group dynamics', 'Thrive in high-energy group settings'] },
   { id: 't8_q3', traitId: 't8', domain: 'general', prompt: 'Connection feels strongest when…', leftAnchor: 'One person deeply understands me', rightAnchor: 'Collective energy and shared moments', options: ['One person deeply understands me', 'Conversations feel personal and meaningful', 'Depth matters more than group size', 'Both depth and shared experience matter', 'Shared experiences with several people', 'Strong sense of group belonging', 'Collective energy and shared moments'] },
   { id: 't8_q4', traitId: 't8', domain: 'general', prompt: 'When meeting new people, you…', leftAnchor: 'Focus on deeper connection with a few', rightAnchor: 'Easily connect with many and enjoy variety', options: ['Focus on deeper connection with a few', 'Prefer fewer, meaningful conversations', 'Meet some, but focus on select people', 'Balance meeting many and going deeper', 'Meet many, then choose a few to deepen', 'Enjoy interacting with many people', 'Easily connect with many and enjoy variety'] },

   { id: 't9_q1', traitId: 't9', domain: 'general', prompt: 'In stressful situations, your immediate reaction is…', leftAnchor: 'Strong and hard to control', rightAnchor: 'Steady and composed', options: ['Strong and hard to control', 'Intense and quickly activated', 'Noticeable but manageable', 'Varies depending on situation', 'Controlled with some emotional impact', 'Calm and aware', 'Steady and composed'] },
   { id: 't9_q2', traitId: 't9', domain: 'general', prompt: 'In emotionally intense moments, you…', leftAnchor: 'React quickly and strongly', rightAnchor: 'Stay highly steady and controlled', options: ['React quickly and strongly', 'Feel overwhelmed in the moment', 'Experience noticeable emotional spikes', 'Adjust based on context', 'Stay fairly composed', 'Remain calm and aware', 'Stay highly steady and controlled'] },
   { id: 't9_q3', traitId: 't9', domain: 'general', prompt: 'After setbacks or stress, you usually…', leftAnchor: 'Stay affected for a long time', rightAnchor: 'Return to clarity with little residue', options: ['Stay affected for a long time', 'Carry emotional impact for days', 'Take time to recover', 'Recover depending on situation', 'Reset fairly quickly', 'Regain balance quickly', 'Return to clarity with little residue'] },
   { id: 't9_q4', traitId: 't9', domain: 'general', prompt: 'After criticism or conflict, you…', leftAnchor: 'Stay mentally stuck for long', rightAnchor: 'Let go quickly and move on', options: ['Stay mentally stuck for long', 'Feel affected deeply', 'Need time to reset', 'Process at a moderate pace', 'Move forward after reflection', 'Recover quickly and refocus', 'Let go quickly and move on'] },

   { id: 't10_q1', traitId: 't10', domain: 'general', prompt: 'When working on important but uninteresting tasks…', leftAnchor: 'Avoid or delay them', rightAnchor: 'Complete regardless of motivation', options: ['Avoid or delay them', 'Often postpone them', 'Struggle but eventually complete them', 'Complete based on importance', 'Usually complete them on time', 'Consistently follow through', 'Complete regardless of motivation'] },
   { id: 't10_q2', traitId: 't10', domain: 'general', prompt: 'When no one is monitoring your work, you…', leftAnchor: 'Lose focus or delay tasks', rightAnchor: 'Maintain full discipline independently', options: ['Lose focus or delay tasks', 'Work inconsistently', 'Stay somewhat accountable', 'Maintain moderate discipline', 'Stay mostly responsible', 'Remain disciplined and focused', 'Maintain full discipline independently'] },
   { id: 't10_q3', traitId: 't10', domain: 'general', prompt: 'Long-term commitments are usually…', leftAnchor: 'Strong start, weak follow-through', rightAnchor: 'Consistent from start to finish', options: ['Strong start, weak follow-through', 'Difficult to sustain', 'Inconsistent over time', 'Maintained with some variation', 'Fairly consistent', 'Strong and reliable', 'Consistent from start to finish'] },
   { id: 't10_q4', traitId: 't10', domain: 'general', prompt: 'Systems like habits and deadlines feel…', leftAnchor: 'Restrictive and easy to ignore', rightAnchor: 'Essential for execution', options: ['Restrictive and easy to ignore', 'Difficult to maintain', 'Slightly uncomfortable', 'Useful depending on situation', 'Helpful for consistency', 'Strongly supportive', 'Essential for execution'] },

   { id: 't11_q1', traitId: 't11', domain: 'general', prompt: 'When making important decisions, you…', leftAnchor: 'Rely heavily on guidance', rightAnchor: 'Take full ownership independently', options: ['Rely heavily on guidance', 'Prefer clear direction from others', 'Use guidance with some independence', 'Balance guidance and self-direction', 'Prefer independence with occasional input', 'Decide mostly on your own', 'Take full ownership independently'] },
   { id: 't11_q2', traitId: 't11', domain: 'general', prompt: 'When working with others, you perform best when…', leftAnchor: 'Roles and steps are clearly directed', rightAnchor: 'Full control over approach and execution', options: ['Roles and steps are clearly directed', 'Mostly guided with defined structure', 'Some direction with flexibility', 'Balanced between guidance and freedom', 'Freedom with occasional alignment', 'Strong personal ownership', 'Full control over approach and execution'] },
   { id: 't11_q3', traitId: 't11', domain: 'general', prompt: 'When closely supervised, you tend to…', leftAnchor: 'Follow direction closely without deviation', rightAnchor: 'Strongly prefer full independence', options: ['Follow direction closely without deviation', 'Prefer staying aligned with guidance', 'Work within structure with some independence', 'Adjust based on situation', 'Prefer some independence within structure', 'Resist excessive control', 'Strongly prefer full independence'] },
   { id: 't11_q4', traitId: 't11', domain: 'general', prompt: 'When facing challenges, you usually…', leftAnchor: 'Seek help immediately', rightAnchor: 'Rely on yourself before seeking help', options: ['Seek help immediately', 'Prefer guidance before acting', 'Ask for help when needed', 'Balance self-effort and support', 'Try solving independently first', 'Prefer solving on your own', 'Rely on yourself before seeking help'] },
];


module.exports={PERSONALITY_TRAITS,PERSONALITY_QUESTIONS};
